export const projects = [
    {
        id: 1,
        key: 1,
        title: "Togo",
        subtitle: "TODO",
        description: "TODO",
        logoUrl: "./logo5.png",
        videoUrl: "./a.mp4",
    },
    {
        id: 2,
        key: 2,
        title: "Kitebi",
        subtitle: "Book/Audiobook reading mobile application",
        description: "This app allows you to read books and listen to" +
            " audiobooks published by the Ministry of Cultural Affairs of Tunisia.",
        logoUrl: "./logo1.png",
        videoUrl: "./vid.mp4",
    },
    {
        id: 3,
        key: 3,
        title: "Khedemti",
        subtitle: "TODO",
        description: "TODO",
        logoUrl: "./logo4.png",
        videoUrl: "./a.mp4",
    },
    {
        id: 4,
        key: 4,
        title: "Chicky",
        subtitle: "TODO",
        description: "TODO",
        logoUrl: "./logo2.png",
        videoUrl: "./a.mp4",
    },
    {
        id: 5,
        key: 5,
        title: "Rose",
        subtitle: "TODO",
        description: "TODO",
        logoUrl: "./logo3.png",
        videoUrl: "./a.mp4",
    },
    {
        id: 1,
        key: 6,
        title: "Togo",
        subtitle: "TODO",
        description: "TODO",
        logoUrl: "./logo5.png",
        videoUrl: "./a.mp4",
    },
    {
        id: 2,
        key: 7,
        title: "Kitebi",
        subtitle: "Book/Audiobook reading mobile application",
        description: "This app allows you to read books and listen to" +
            " audiobooks published by the Ministry of Cultural Affairs of Tunisia.",
        logoUrl: "./logo1.png",
        videoUrl: "./vid.mp4",
    },
    {
        id: 3,
        key: 8,
        title: "Khedemti",
        subtitle: "TODO",
        description: "TODO",
        logoUrl: "./logo4.png",
        videoUrl: "./a.mp4",
    },
];

export const skills = [
    "Swift",
    "Kotlin",
    "Flutter",
    "JavaScript",
    "ReactJS",
    "NodeJS",
];
